### ISSUE TITLE
[Tests] lots of tests fail (104) comparing `master` to `main`

### ISSUE THREAD

**Issue by rubengmurray** [reduckted/GitWebLinks#46]
Looks like a change in the default branch is causing many tests to fail.. as an example:

```
  93) Link handlers
       Visual Studio Team Services
         createUrl
           ssh with protocol:

      Link does not match the expected result
      + expected - actual

      -https://foo.visualstudio.com/_git/bar?path=%2Fsrc%2Ffile.txt&version=GBmain
      +https://foo.visualstudio.com/_git/bar?path=%2Fsrc%2Ffile.txt&version=GBmaster
      
        at /Users/reecedaniels/dev/general/_OPEN-SOURCE-REPOS/GitWebLinks/vscode/out-test/test/handlers.test.js:174:96
        at Generator.next (<anonymous>)
        at fulfilled (out-test/test/handlers.test.js:5:58)
```

I have 104 failures locally

**Comment by reduckted** [comment]
Thanks! Fixed in 08b67b6b101d01b3e64eee752ea23be1c54d3395.
